[project]
name = "calhacks-continual-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mss>=10.1.0",
    "aiohttp>=3.9.0",
]
